{
  imports = [
    ./config.nix
    ./gtk.nix
    ./programs/alacritty.nix
    ./programs/git.nix
    ./programs/hyperland
    ./programs/kitty.nix
    ./programs/scripts
    ./programs/ssh.nix
    ./programs/sway
    ./programs/waybar
    ./programs/zsh.nix
    ./roles/dev.nix
    ./roles/graphical.nix
    ./roles/shell.nix
    ./roles/sway.nix
    ./secrets
    ./xdg.nix
  ];
}
