name: build

on:
  push:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  build-emacs-linux:
    uses: ./.github/workflows/build-steps.yaml
    with:
      os: ubuntu-latest
      build-command: nix build .#emacs -L
    secrets: inherit

  build-linux:
    needs: build-emacs-linux
    strategy:
      matrix:
        host: [ix, omen, sigil]
    uses: ./.github/workflows/build-steps.yaml
    with:
      os: ubuntu-latest
      build-command: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel -L
    secrets: inherit

  build-emacs-darwin:
    uses: ./.github/workflows/build-steps.yaml
    with:
      os: macos-latest
      build-command: nix build .#emacs -L
    secrets: inherit

  build-darwin:
    needs: build-emacs-darwin
    strategy:
      matrix:
        host: [halo, ampere]
    uses: ./.github/workflows/build-steps.yaml
    with:
      os: macos-latest
      build-command: nix build .#darwinConfigurations.${{ matrix.host }}.config.system.build.toplevel -L
    secrets: inherit
