name: build-steps

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      build-command:
        required: true
        type: string
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true

jobs:
  build:
    environment: CI
    runs-on: ${{ inputs.os }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@main
        if: ${{ inputs.os == 'ubuntu-latest' }}
        with:
          hatchet-protocol: 'holster'
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= psyclyx.cachix.org-1:UFwKXEDn3gLxIW9CeXGdFFUzCIjj8m6IdAQ7GA4XfCk=
            substituters = https://nix-community.cachix.org https://psyclyx.cachix.org
      - run: ${{ inputs.build-command }}
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
