name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        host: [ix, omen, sigil, tleilax]
    uses: ./.github/workflows/build-steps.yaml
    with:
      os: ubuntu-latest
      build-command: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel -L
    secrets: inherit

  build-darwin:
    strategy:
      fail-fast: false
      matrix:
        host: [halo]
    uses: ./.github/workflows/build-steps.yaml
    with:
      os: macos-latest
      build-command: nix build .#darwinConfigurations.${{ matrix.host }}.config.system.build.toplevel -L
    secrets: inherit
