name: "update lockfile"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  lockfile:
    environment: CI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v16
        with:
          name: ${{ vars.CACHIX_CACHE_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipAddingSubstituter: true
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v25
        with:
          token: ${{ secrets.GH_TOKEN_UPDATE }}
